import { NgModule } from '@angular/core';
import {
  RlsAmountComponent,
  RlsAvatarComponent,
  RlsBadgeComponent,
  RlsBallotComponent,
  RlsBottomSheetComponent,
  RlsButtonActionComponent,
  RlsButtonComponent,
  RlsCheckboxComponent,
  RlsFieldAutocompleteComponent,
  RlsFieldDateComponent,
  RlsFieldDateRangeComponent,
  RlsFieldMoneyComponent,
  RlsFieldNumberComponent,
  RlsFieldPasswordComponent,
  RlsFieldSelectComponent,
  RlsFieldTextComponent,
  RlsLabelCheckboxComponent,
  RlsLabelComponent,
  RlsLabelRadiobuttonComponent,
  RlsLabelSwitchComponent,
  RlsPaginationComponent,
  RlsPickerDateComponent,
  RlsPickerDateRangeComponent,
  RlsPickerDayRangeComponent,
  RlsPosterComponent,
  RlsProgressBarComponent,
  RlsProgressCircularComponent,
  RlsRadiobuttonComponent,
  RlsSkeletonComponent,
  RlsSkeletonTextComponent,
  RlsSwitchComponent,
  RlsTabularTextComponent
} from '../../../../projects';
import { HomePage } from './home.page';
import { HomePageRouting } from './home.page.routing';

@NgModule({
  declarations: [HomePage],
  imports: [
    HomePageRouting,
    RlsBadgeComponent,
    RlsLabelComponent,
    RlsAvatarComponent,
    RlsCheckboxComponent,
    RlsFieldTextComponent,
    RlsFieldNumberComponent,
    RlsTabularTextComponent,
    RlsAmountComponent,
    RlsButtonComponent,
    RlsFieldMoneyComponent,
    RlsButtonActionComponent,
    RlsFieldPasswordComponent,
    RlsPosterComponent,
    RlsProgressBarComponent,
    RlsProgressCircularComponent,
    RlsRadiobuttonComponent,
    RlsSkeletonComponent,
    RlsSkeletonTextComponent,
    RlsSwitchComponent,
    RlsBallotComponent,
    RlsLabelCheckboxComponent,
    RlsLabelRadiobuttonComponent,
    RlsLabelSwitchComponent,
    RlsBottomSheetComponent,
    RlsPickerDateComponent,
    RlsFieldDateComponent,
    RlsPickerDayRangeComponent,
    RlsPaginationComponent,
    RlsFieldSelectComponent,
    RlsFieldAutocompleteComponent,
    RlsPickerDateRangeComponent,
    RlsFieldDateRangeComponent
  ]
})
export class HomePageModule {}
